### ISSUE TITLE
Migrate from `serviceworker-webpack-plugin`

### ISSUE THREAD

**Issue by coderaiser** [tatethurston/service-worker-webpack#1]
Could you please help me migrate from [serviceworker-webpack-plugin](https://github.com/oliviertassinari/serviceworker-webpack-plugin), here is my [`webpack` config](https://github.com/coderaiser/cloudcmd/blob/master/.webpack/js.js)

**Comment by tatethurston** [comment]
Hey @coderaiser I believe the example outlined in the readme covers your use case. Try it out and let me know if you run into any issues.

**Comment by tatethurston** [comment]
I took a look at your [service worker](https://github.com/coderaiser/cloudcmd/blob/master/client/sw/sw.js) and the default service worker generated by workbox “under the hood” may meet your needs. You know your application better than I do, so you can best vet the behavior. I’m happy to answer any questions.
